sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: a123456
  alioss:
    bucket-name: sky-itcast-water
    access-key-id: <your-aliyun-access-key-id>
    access-key-secret: <your-aliyun-access-key-secret>
    endpoint: oss-cn-beijing.aliyuncs.com
  redis:
    host: localhost
    port: 6379
    password: a123456
    database: 0
  wechat:
    appid: wxc7fe573329f28e3e
    secret: 0d82c49025c1daefc00e113b98c3c6ba
