sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: a123456
  alioss:
    bucket-name: sky-itcast-water
    access-key-id: <your-aliyun-access-key-id>
    access-key-secret: <your-aliyun-access-key-secret>
    endpoint: oss-cn-beijing.aliyuncs.com
  redis:
    host: localhost
    port: 6379
    password: a123456
    database: 0
  wechat:
    appid: wxc7fe573329f28e3e
    secret: 0d82c49025c1daefc00e113b98c3c6ba
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435Wxpay435434323FFDuv3
    wechatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://6619cf50.r6.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://6619cf50.r6.cpolar.top/notify/refundSuccess
